In [1]:
test = "test"

In [2]:
test = "test.qwe"

In [3]:
print(test)

test.qwe


In [5]:
['a', 'b', 'c'] + [1, 2, 3]



['a', 'b', 'c', 1, 2, 3]

In [7]:
type(lambda x: x+1)

function

In [10]:
[x**2 for x in range(10)] 

[0, 1, 4, 9, 16, 25, 36, 49, 64, 81]

In [13]:
import numpy as np

In [19]:
n = np.arange(0,36, 1)
n

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35])

In [21]:
n = n.reshape(6, 6)
n

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35]])

In [29]:
n.reshape(36)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35])

In [32]:
n.reshape(36)[::7]

array([ 0,  7, 14, 21, 28, 35])

In [34]:
n1= np.arange(0, 36, 1)
n1

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35])

In [38]:
n1 = n1.reshape(6, 6)
n1

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35]])

In [40]:
n1.reshape(36)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35])

In [44]:
n1[2:4, 2:4]

array([[14, 15],
       [20, 21]])